### ISSUE TITLE
Choice of male and female voices ?

### ISSUE THREAD

**Issue by motorsep** [DrawnzerGames/SpeakMyWords#2]
It's not on the readme, so I am wondering if it's possible to choose between male and female version of voices?

I know on Android 7 there are quite a few male and female options in text-to-speech settings.

**Comment by ANURAGX** [comment]
Thanks for the feature request.
Please refer this link 
https://stackoverflow.com/questions/9815245/android-text-to-speech-male-voice

I myself feel like it should not be possible, but its quite tricky and unstable to implement because different voice depends upon the language pack installed on user's Android Phone.

**Comment by ANURAGX** [comment]
Thanks for the feature request.
Please refer this link 
https://stackoverflow.com/questions/9815245/android-text-to-speech-male-voice

I myself feel like it should not be possible, but its quite tricky and unstable to implement because different voice depends upon the language pack installed on user's Android Phone.

**Comment by motorsep** [comment]
If you look at Saad Mahmud's reply in that link, you'll see how to dynamically change voice type. 
I am looking into using this plugin to make my NPCs of various gender talk and unfortunately without ability to set male/female voice it's pretty much useless :(
